apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: test-service
spec:
  selector:
    app.kubernetes.io/name: personal-profile
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
