apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  template:
    spec:
      containers:
        - name: mycontainer
          image: "public.ecr.aws/n2d8l6y5/web-app:70ca5d945333499660b1dc32d0a6df2a131e11a1"
